// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Tokens {
    name:        string;
    account:     string;
    symbol:      string;
    precision:   number;
    logo:        string;
    website:     null | string;
    desc?:       DescClass | string;
    links?:      Links;
    whitepaper?: string;
}

export interface DescClass {
    en:  string;
    [language: string]: string;
}

export interface Links {
    twitter?:  string;
    telegram?: string;
    medium?:   string;
    facebook?: string;
    reddit?:   string;
    github?:   string;
    steemit?:  string;
    wechat?:   string;
}
